/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradlecage;

import tech.tablesaw.api.DoubleColumn;
import tech.tablesaw.api.Row;
import tech.tablesaw.api.StringColumn;
import tech.tablesaw.api.Table;

public class App {

    static Integer N_MFCC = 26;

    public static void main(String[] args) throws Exception {

        String audio_file_path = "data/audio_test/Wu0427";

        // Create DataFrame
        String[] col_names = {"Bin_No","Cough_No","Win_No","ZCR","Kurtosis","LogE"};
        StringColumn feat_colNames = StringColumn.create("feat_colNames", col_names);

        for (int i = 1; i < N_MFCC+1; i++) {
            feat_colNames.append("MFCC_"+i);
        }
        for (int i = 1; i < N_MFCC+1; i++) {
            feat_colNames.append("MFCC_D_"+i);
        }
        for (int i = 1; i < N_MFCC+1; i++) {
            feat_colNames.append("MFCC_2D_"+i);
        }

        for (String string : feat_colNames) {
            System.out.println(string);
        }


    }

    

}
